language: smalltalk
sudo: false

# Select compatible Smalltalk image(s)
smalltalk:
  #- Squeak-trunk
  - Squeak-5.1
  - Squeak-5.0

matrix:
  include:
    - language: python
      smalltalk:
      before_install:
        - sudo apt-get install libharfbuzz-dev libfreetype6-dev
        - python3 setup.py install
      python: "3.5"
      script: pytest
      sudo: required

before_script:
  # Move testFiles into smalltalkCI build directory
  - "[[ -d $SMALLTALK_CI_BUILD/BP2016H1 ]] || mkdir -p $SMALLTALK_CI_BUILD/BP2016H1"
  - ln -s $TRAVIS_BUILD_DIR/testFiles $SMALLTALK_CI_BUILD/BP2016H1
  - ln -s $TRAVIS_BUILD_DIR/assets $SMALLTALK_CI_BUILD/BP2016H1
