language: smalltalk
sudo: false

before_script:
  # Move testFiles into smalltalkCI build directory
  - "[[ -d $SMALLTALK_CI_BUILD/BP2016H1 ]] || mkdir -p $SMALLTALK_CI_BUILD/BP2016H1"
  - ln -s $TRAVIS_BUILD_DIR/testFiles $SMALLTALK_CI_BUILD/BP2016H1
  - ln -s $TRAVIS_BUILD_DIR/assets $SMALLTALK_CI_BUILD/BP2016H1

matrix:
  include:
    - language: python
      dist: trusty
      smalltalk:
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install libharfbuzz-dev libfreetype6-dev python3-pip python3-dev -y
        - git clone -b master git://github.com/libgit2/libgit2.git
        - cd libgit2
        - mkdir build && cd build
        - cmake ..
        - make && sudo make install
        - sudo ldconfig
        - cd ../..
      install:
        - sudo pip3 install -U setuptools
        - pip3 install -r requirements.txt
        - sudo python3 setup.py install
        - "sudo chown -R $USER:$USER ."
      before_script:
      python: "3.5"
      script: python3 setup.py test
      sudo: required
    - language: smalltalk
      sudo: false
      smalltalk:
        Squeak-5.1
